### ISSUE TITLE
Support for files without an extension

### ISSUE THREAD

**Issue by nesl247** [dderevjanik/vscode-icons-js#12]
Do you plan to add support for files without an extension, such as `Jenkinsfile`? `vscode-icons` already has support for it.

**Comment by dderevjanik** [comment]
Hi,
thank you very much for creating an issue. It looks like I need to update vscode-icons to newer version 7.24.0. 

ref: https://github.com/vscode-icons/vscode-icons/blob/master/CHANGELOG.md#7240-june-20-2018

**Comment by dderevjanik** [comment]
@nesl247 with 7.25 update it works as expected :)

You can try it here:
https://dderevjanik.github.io/vscode-icons-js-example/

**Comment by nesl247** [comment]
Thanks! Now to get the github extension updated.

**Comment by nesl247** [comment]
Actually, I didn't realize you wrote both. Mind updating the github extension?

**Comment by dderevjanik** [comment]
Definetly, but it will take a time, because there's an opened issue which I'm working on. I will try to do my best.

Thanks

**Comment by dderevjanik** [comment]
Okay, github extension is updated to version 1.13 that matches vscode-icons version 7.52.
You can now enjoy `Jenkinsfile` :)

**Comment by nesl247** [comment]
Thanks!
